### ISSUE TITLE
Montar Introdução

### ISSUE THREAD

**Issue by joaopedro2017** [Seminario-2/Sharing-Ideas-using-GitHub#1]

**Comment by sauloemidio** [comment]
Git HUb
 Branch e mergers como funcionará a branch? Trabalho está pronto, mas surge a necessidade de alterar algumas partes dele como forma de melhorá-lo. Além disso, você precisa manter estas alterações tanto no computador de casa quanto da instituição de ensino. Com isso temos um problema, se você começa a alterar os arquivos em casa, para na metade da implementação, e precisa terminar na instituição de ensino, como você iria comitar tudo pela metade e deixar o trabalho pela metade incompleto?

Para isso existe o conceito de branch, que é justamente ramificar o seu projeto em 2, como se cada um deles fosse um repositório, e depois juntá-lo novamente. 


Organização = disciplina
Repositório = atividades e trabalhos propostos na sala de aula

 Peaple = adiciona pessoas (convite é enviado por e-mail para confirmação)

Equipes =  Acesso ao repositório de forma flexível onde pode ser adicionado repositórios às equipes com níveis de acesso mais flexíveis (admin, gravação, leitura).
